version: "3.1"

services:
  app:
    container_name: go-restful-api_app
    image: go-restful-api/app
    build:
      context: api
      dockerfile: ./Dockerfile
    ports:
      - 9090:8080
    volumes:
      - ./api/:/app
    env_file:
      - .env
    networks:
      - container-link
  db:
    container_name: go-restful-api_db
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/access.cnf:/home/access.cnf
    command: bash -c 'usermod -o -u $LINUX_MYSQL_UID mysql; groupmod -o -g $LINUX_MYSQL_GID mysql; chown -R mysql:root /var/run/mysqld/ /var/log/mysql/ /var/lib/mysql/; /entrypoint.sh mysqld --user=mysql --console'
    env_file:
      - .env.db
    networks: 
      - container-link

networks:
  default:
    external:
      name: bridge
  container-link:
    name: go-restful-api_link